"""Initial schema with SQLModel

Revision ID: 6f382f313048
Revises: 
Create Date: 2026-10-08 16:48:26.994941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f382f313048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_profiles', 'profile_df_json',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Datos del perfil topográfico en JSON comprimible',
               existing_nullable=True)
    op.alter_column('project_profiles', 'veg_df_json',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Datos del perfil de vegetación procesado en JSON',
               existing_nullable=True)
    op.alter_column('project_profiles', 'exclusions_json',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Zonas de exclusión de vegetación aplicadas',
               existing_nullable=True)
    op.alter_column('project_profiles', 'calculated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('project_id'), table_name='project_profiles')
    op.create_index(op.f('ix_project_profiles_project_id'), 'project_profiles', ['project_id'], unique=True)
    op.alter_column('project_rf_settings', 'frequency_ghz',
               existing_type=mysql.DECIMAL(precision=6, scale=3),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'5.800'"))
    op.alter_column('project_rf_settings', 'tx_power_dbm',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'24.00'"))
    op.alter_column('project_rf_settings', 'required_capacity_mbps',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'500.00'"))
    op.alter_column('project_rf_settings', 'other_losses_db',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'2.00'"))
    op.alter_column('project_rf_settings', 'k_factor',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'1.333'"))
    op.create_index(op.f('ix_project_rf_settings_project_id'), 'project_rf_settings', ['project_id'], unique=True)
    op.drop_column('project_rf_settings', 'updated_at')
    op.drop_column('project_rf_settings', 'created_at')
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               comment=None,
               existing_comment='Nombre único del proyecto',
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='Descripción u observaciones del enlace',
               existing_nullable=True)
    op.alter_column('projects', 'format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               existing_server_default=sa.text("'SAF-Link-Planner-Project'"))
    op.alter_column('projects', 'version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False,
               existing_server_default=sa.text("'V5.5.5'"))
    op.alter_column('projects', 'elevation_provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False,
               existing_server_default=sa.text("'Open-Meteo (Gratuito / Copernicus DEM)'"))
    op.alter_column('projects', 'ee_project',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False,
               existing_server_default=sa.text("'saf-link-planner'"))
    op.alter_column('projects', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_project_name'), table_name='projects')
    op.drop_index(op.f('name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.alter_column('radios', 'manufacturer',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Fabricante (ej. Mimosa, SAF, Cambium)',
               existing_nullable=False)
    op.alter_column('radios', 'model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Modelo del equipo',
               existing_nullable=False)
    op.alter_column('radios', 'frequency_min_ghz',
               existing_type=mysql.DECIMAL(precision=6, scale=3),
               type_=sa.Float(),
               comment=None,
               existing_comment='Frecuencia mínima de operación en GHz',
               existing_nullable=True)
    op.alter_column('radios', 'frequency_max_ghz',
               existing_type=mysql.DECIMAL(precision=6, scale=3),
               type_=sa.Float(),
               comment=None,
               existing_comment='Frecuencia máxima de operación en GHz',
               existing_nullable=True)
    op.alter_column('radios', 'max_output_power_dbm',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Potencia de transmisión máxima TX (dBm)',
               existing_nullable=True)
    op.alter_column('radios', 'integrated_antenna_gain_dbi',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Ganancia si tiene antena integrada (dBi)',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('radios', 'throughput_gbps',
               existing_type=mysql.DECIMAL(precision=6, scale=3),
               type_=sa.Float(),
               comment=None,
               existing_comment='Capacidad máxima de throughput (Gbps)',
               existing_nullable=True)
    op.alter_column('radios', 'bandwidths_mhz',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Lista de anchos de canal soportados en MHz [20, 40, 80, 160]',
               existing_nullable=True)
    op.alter_column('radios', 'mimo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Configuración MIMO (ej. 2x2, 4x4, SISO)',
               existing_nullable=True)
    op.alter_column('radios', 'modulation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Esquemas de modulación soportados (ej. BPSK a 1024QAM)',
               existing_nullable=True)
    op.alter_column('radios', 'rx_sensitivity_dbm',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Mapeo de sensibilidades por canal en formato JSON',
               existing_nullable=True)
    op.alter_column('radios', 'source_file',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Nombre del PDF datasheet de origen',
               existing_nullable=True)
    op.alter_column('radios', 'notes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='Notas y observaciones adicionales del equipo',
               existing_nullable=True)
    op.alter_column('radios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('radios', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_radio_freq'), table_name='radios')
    op.drop_index(op.f('idx_radio_mfg'), table_name='radios')
    op.drop_index(op.f('model'), table_name='radios')
    op.create_index(op.f('ix_radios_manufacturer'), 'radios', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_radios_model'), 'radios', ['model'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radios_model'), table_name='radios')
    op.drop_index(op.f('ix_radios_manufacturer'), table_name='radios')
    op.create_index(op.f('model'), 'radios', ['model'], unique=True)
    op.create_index(op.f('idx_radio_mfg'), 'radios', ['manufacturer'], unique=False)
    op.create_index(op.f('idx_radio_freq'), 'radios', ['frequency_min_ghz', 'frequency_max_ghz'], unique=False)
    op.alter_column('radios', 'updated_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('radios', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('radios', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Notas y observaciones adicionales del equipo',
               existing_nullable=True)
    op.alter_column('radios', 'source_file',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Nombre del PDF datasheet de origen',
               existing_nullable=True)
    op.alter_column('radios', 'rx_sensitivity_dbm',
               existing_type=mysql.JSON(),
               comment='Mapeo de sensibilidades por canal en formato JSON',
               existing_nullable=True)
    op.alter_column('radios', 'modulation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Esquemas de modulación soportados (ej. BPSK a 1024QAM)',
               existing_nullable=True)
    op.alter_column('radios', 'mimo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Configuración MIMO (ej. 2x2, 4x4, SISO)',
               existing_nullable=True)
    op.alter_column('radios', 'bandwidths_mhz',
               existing_type=mysql.JSON(),
               comment='Lista de anchos de canal soportados en MHz [20, 40, 80, 160]',
               existing_nullable=True)
    op.alter_column('radios', 'throughput_gbps',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=3),
               comment='Capacidad máxima de throughput (Gbps)',
               existing_nullable=True)
    op.alter_column('radios', 'integrated_antenna_gain_dbi',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               comment='Ganancia si tiene antena integrada (dBi)',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('radios', 'max_output_power_dbm',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               comment='Potencia de transmisión máxima TX (dBm)',
               existing_nullable=True)
    op.alter_column('radios', 'frequency_max_ghz',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=3),
               comment='Frecuencia máxima de operación en GHz',
               existing_nullable=True)
    op.alter_column('radios', 'frequency_min_ghz',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=3),
               comment='Frecuencia mínima de operación en GHz',
               existing_nullable=True)
    op.alter_column('radios', 'model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Modelo del equipo',
               existing_nullable=False)
    op.alter_column('radios', 'manufacturer',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Fabricante (ej. Mimosa, SAF, Cambium)',
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('idx_project_name'), 'projects', ['name'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'ee_project',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True,
               existing_server_default=sa.text("'saf-link-planner'"))
    op.alter_column('projects', 'elevation_provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True,
               existing_server_default=sa.text("'Open-Meteo (Gratuito / Copernicus DEM)'"))
    op.alter_column('projects', 'version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'V5.5.5'"))
    op.alter_column('projects', 'format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("'SAF-Link-Planner-Project'"))
    op.alter_column('projects', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Descripción u observaciones del enlace',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               comment='Nombre único del proyecto',
               existing_nullable=False)
    op.add_column('project_rf_settings', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('project_rf_settings', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_project_rf_settings_project_id'), table_name='project_rf_settings')
    op.alter_column('project_rf_settings', 'k_factor',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=4, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text("'1.333'"))
    op.alter_column('project_rf_settings', 'other_losses_db',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'2.00'"))
    op.alter_column('project_rf_settings', 'required_capacity_mbps',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'500.00'"))
    op.alter_column('project_rf_settings', 'tx_power_dbm',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'24.00'"))
    op.alter_column('project_rf_settings', 'frequency_ghz',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text("'5.800'"))
    op.drop_index(op.f('ix_project_profiles_project_id'), table_name='project_profiles')
    op.create_index(op.f('project_id'), 'project_profiles', ['project_id'], unique=True)
    op.alter_column('project_profiles', 'calculated_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('project_profiles', 'exclusions_json',
               existing_type=mysql.JSON(),
               comment='Zonas de exclusión de vegetación aplicadas',
               existing_nullable=True)
    op.alter_column('project_profiles', 'veg_df_json',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='Datos del perfil de vegetación procesado en JSON',
               existing_nullable=True)
    op.alter_column('project_profiles', 'profile_df_json',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='Datos del perfil topográfico en JSON comprimible',
               existing_nullable=True)
    # ### end Alembic commands ###
